server:
  port: 8084

spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    schemas: public
  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:postgresql://localhost:5432/music_media
    username: postgres
    password: 1111

  application:
    name: media-service

services:
  queue-service:
    url: http://localhost:8083